### PR TITLE
made code more readable

### PR DESCRIPTION
**Pull request by rutvikpadhiyar000**
Just suggestion for improvement.

### CODE REVIEW

**Review by CodeAsherPlayz — APPROVED** [review]

**Comment by CodeAsherPlayz** [comment]
Closes #6

**Review by CodeAsherPlayz — APPROVED** [review]
Sorry but I actually am not an experienced Coder so can you explain the lines to me before I merge? Thanks!

**Comment by CodeAsherPlayz** [comment]
Never mind, it's okay! I figured it out on my laptop because I was using my phone yesterday. Hope you can help out in this repository :D Thanks for dropping by!

**Comment by CodeAsherPlayz** [comment]
There were some conflicts between the two files so I manually copied and pasted the code. Thanks!

**Comment by rutvikpadhiyar000** [comment]
Ok thanks.

**Comment by rutvikpadhiyar000** [comment]
I don't know how to do it but i think github has feature to add to-do's you can check it out so others can know what to do next.

**Pull request closed without merging**
